### ISSUE TITLE
WSL2Install Ubuntu 20.04

### ISSUE THREAD

**Issue by Layer8Err** [TimmKroe/win10improvements#8]
https://github.com/TimmKroe/win10improvements/blob/master/modules/tweaks/WSL2Install.ps1

If you want to add Ubuntu 20.04 support to the WSL2Install.ps1 script, the code is now available:
https://github.com/Layer8Err/WSL2setup/blob/master/WSL2_Install.ps1

I had to use fiddler to get the 20.04 URI

**Comment by TimmKroe** [comment]
![grafik](https://user-images.githubusercontent.com/27803956/84512405-38868c80-acc8-11ea-896f-01432e8ffcc7.png)
Your awesome code still has some problems. I will fix them.

**Comment by Layer8Err** [comment]
Thank you for the feedback, I'll need to fork and fix.
